### ISSUE TITLE
Comick Extension Bug 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [komikku-app/komikku-extensions#12]
### Source information

Comick - version 1.4.42

### Source language

English 

### Steps to reproduce

1. Open Comick
2. Check if the extension is working
3. No further notice of updating manga/comics.

![Screenshot_20240331_162156](https://github.com/komikku-app/komikku-extensions/assets/104534608/2905b2eb-9054-4834-8edf-b1fdbeec0e8a)
![Screenshot_20240331_162212](https://github.com/komikku-app/komikku-extensions/assets/104534608/85368b15-8707-482e-8ad5-263a5b88b470)

### Expected behavior

I don't know why, but the comick extension was working yesterday, so I'm assuming today might be different. 

### Actual behavior

Comick extension I updated in the past had never experienced this situation before so this is the first time for me. 

### Mihon/Tachiyomi version

Preview r20

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
Did you tried checking Webview?
