### ISSUE TITLE
Merge to upstream for any missing extension

### ISSUE THREAD

**Issue by 0Ha16wA5** [komikku-app/komikku-extensions#16]
### Describe why this should be added

Instead of duplicating work, why not merge it to upstream (Keiyoushi)?

Especially for extension like `EveriaClubCom`, `Misskon`, `Xinmeitulu` improvement, etc...

More eye to review, more code quality, more code improvement.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
I did that before but some of the changes were more of my opinion so they rejected it and told me to keep it on my own repo.

Also, Komikku app now has a feature of showing related mangas which is not on Mihon so those changes will surely get rejected.

However, I'm still merging improvements that could be accepted to the upstream's repo.
