### ISSUE TITLE
3Hentai : It is duplicated twice.

### ISSUE THREAD

**Issue by OtakuArab** [komikku-app/komikku-extensions#43]
### Source information

3Hentai

### Source language

all

### Steps to reproduce

There are two versions of the application, we hope to delete one of them

### Expected behavior

There must be one copy.

### Actual behavior

But there are two versions that are repeated.

### Mihon/Tachiyomi version

1.11.12

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
I don't think there are 2 versions of this. You might be mistaken it with Keiyoushi's version which has a different package name and hence seeing 2 versions at the same time.
