### ISSUE TITLE
Re Manga : redundant

### ISSUE THREAD

**Issue by DemonEmperor1** [komikku-app/komikku-extensions#5]
### Source name

Re Manga

### Source language

Arabic 

### Source link

https://re-manga.com/

### Other details

There are two versions of it, the first one is (Re Manga & Re Manga (Arabic)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
They are different sources:
- remanga.org => Russian
- re-manga.com => Arabic

**Comment by cuong-tran** [comment]
Oh right, re-manga.com is added back via keiyoushi with different names. Thanks.
