### ISSUE TITLE
Everia club unoriginal have issues!

### ISSUE THREAD

**Issue by devil6venom** [komikku-app/komikku-extensions#8]
### Source information

Everiaclub.com

### Source language

All

### Steps to reproduce

I installed it, it browse fine
But when i select chapter there is some error!

### Expected behavior

It should open normally and browse any chapter?!

### Actual behavior

It doesn't browse chapters!

### Mihon/Tachiyomi version

Komikku latest

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by cuong-tran** [comment]
It's still working fine on my device. Could you provide more info: which title, photo of the error...

**Comment by cuong-tran** [comment]
never mind, I saw the error

**Comment by devil6venom** [comment]
> never mind, I saw the error

You got the issues? Understand what the problem right?
