### ISSUE TITLE
text not appearing in/ empty dialogue boxes 

### ISSUE THREAD

**Issue by hdg892** [komikku-app/komikku-extensions#86]
### Source information

Snow Machine Translations 1.4.1

### Source language

English

### Steps to reproduce

simply use snowmtl extension and any chapter of any manga there is not showing text in dialogue boxes, everything else is fine

### Expected behavior

dialogue boxes should have text in it

### Actual behavior

dialogue boxes are empty, there is no text in them but everything else is appearing fine

### Mihon/Tachiyomi version

0.15.3

### Android version

10

### Other details

thnk u in advance.....🙇‍♀️🙇‍♂️👍

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cuong-tran** [comment]
some screenshots please. But I doubt this is an extension issue

**Comment by hdg892** [comment]
![Uploading Screenshot_20241205-073722.png…]()

**Comment by cuong-tran** [comment]
upload SS again, wait for it to finish uploading first before submit

**Comment by hdg892** [comment]
![Screenshot_20241205-073722](https://github.com/user-attachments/assets/22e3ebf6-a54b-4fe6-a630-ded0ffb58026)

**Comment by hdg892** [comment]
![Screenshot_20241205-074135](https://github.com/user-attachments/assets/502f8838-bc22-4cca-a561-9439e3f8fda7)

**Comment by cuong-tran** [comment]
interesting

**Comment by hdg892** [comment]
plz try to fix it🙏🙏

**Comment by cuong-tran** [comment]
I submitted a fix on Keiyoushi, wait for it to be merged: https://github.com/keiyoushi/extensions-source/pull/6474

**Comment by hdg892** [comment]
thnk u very very much🙇‍♂️

**Comment by hdg892** [comment]
it is happening agian.  same problem has resurfaced again.

**Comment by hdg892** [comment]
![Screenshot_20241207-063821](https://github.com/user-attachments/assets/f5b52f50-7cce-4533-90e7-a9e4e318fae1)

**Comment by cuong-tran** [comment]
What is the manhwa name?

**Comment by hdg892** [comment]
I Regressed to Level Up Instead of Being a Simp. by the way it is same with every other manga

**Comment by hdg892** [comment]
sorry for asking but can u tell plz me why this seems to keep happening. is this some source problem as it has been only one week since its extension was added

**Comment by cuong-tran** [comment]
source's using various pattern for images. Either the original extension creator didn't check all of it, or source keeps changing it because they couldn't make up their mind. I think the later.
anw, submitted a fix for that, hopefully once for all.

**Comment by hdg892** [comment]
i also think its later one anyway thnk u very much

**Comment by hdg892** [comment]
if you do not mind can u plz tell me where you submitted fix
